# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fIawzBbQvyOc6i1cHigh2dhA6nPclwp
"""

#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

#Load Iris Dataset
iris = load_iris()

#Create Dataframe
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

#Select Only Required Features
df = df[['petal length (cm)', 'petal width (cm)']]
df.head()

# Visualize Dataset
plt.figure(figsize=(6,5))

plt.scatter(df['petal length (cm)'],
            df['petal width (cm)'])

plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.title("Petal Length vs Petal Width")
plt.show()

# Apply K-Means Without Scaling
km = KMeans(n_clusters=3, random_state=42)

y_pred = km.fit_predict(df)

df['Cluster'] = y_pred

df.head()

# Plot Clusters
plt.figure(figsize=(7,6))

plt.scatter(
    df[df.Cluster==0]['petal length (cm)'],
    df[df.Cluster==0]['petal width (cm)'],
    color='red',
    label='Cluster 0'
)

plt.scatter(
    df[df.Cluster==1]['petal length (cm)'],
    df[df.Cluster==1]['petal width (cm)'],
    color='blue',
    label='Cluster 1'
)

plt.scatter(
    df[df.Cluster==2]['petal length (cm)'],
    df[df.Cluster==2]['petal width (cm)'],
    color='green',
    label='Cluster 2'
)

plt.scatter(
    km.cluster_centers_[:,0],
    km.cluster_centers_[:,1],
    color='black',
    marker='*',
    s=250,
    label='Centroids'
)

plt.xlabel("Petal Length")
plt.ylabel("Petal Width")

plt.legend()

plt.show()

# Scale Features
scaler = MinMaxScaler()

df_scaled = scaler.fit_transform(df[['petal length (cm)',
                                     'petal width (cm)']])

# Apply K-Means Again
km = KMeans(n_clusters=3, random_state=42)

y_pred = km.fit_predict(df_scaled)

# Visualize Scaled Clusters
plt.figure(figsize=(6,5))

plt.scatter(
    df_scaled[:,0],
    df_scaled[:,1],
    c=y_pred,
    cmap='rainbow'
)

plt.scatter(
    km.cluster_centers_[:,0],
    km.cluster_centers_[:,1],
    marker='*',
    s=250,
    color='black'
)

plt.xlabel("Scaled Petal Length")
plt.ylabel("Scaled Petal Width")

plt.show()

# Find Optimal K using Elbow Method
sse = []

k_range = range(1,11)

for k in k_range:
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(df_scaled)
    sse.append(km.inertia_)

# Draw Elbow Plot
plt.figure(figsize=(7,5))

plt.plot(k_range, sse, marker='o')

plt.xlabel("Number of Clusters (K)")
plt.ylabel("SSE")

plt.title("Elbow Method")

plt.grid(True)

plt.show()